### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by atoree** [edlea/homebridge-salus-it600#1]
hey, super plugin!  have some trouble getting it to work .. get an error message.  suggestions to make it work?

2/9/2021, 21:40:44] [Salus-iT600] Initializing Salus-iT600 platform...

(node:659) UnhandledPromiseRejectionWarning: StatusError: Internal Server Error
    at ClientRequest.<anonymous> (/usr/lib/node_modules/homebridge-salus-aura/node_modules/bent/src/nodejs.js:133:23)
    at Object.onceWrapper (events.js:417:26)
    at ClientRequest.emit (events.js:310:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:603:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at TLSSocket.socketOnData (_http_client.js:476:22)
    at TLSSocket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    at readableAddChunk (_stream_readable.js:268:9)
    at TLSSocket.Readable.push (_stream_readable.js:209:10)
(node:659) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:659) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by atoree** [comment]
Anyone??

**Comment by xyz4tech** [comment]
Any solution found? Have exactly the same issue.
@edlea Is it a known bug?

**Comment by egorist** [comment]
+1

**Comment by adrmnt** [comment]
Same issue here. @edlea can you help us please with a quick fix? 
Thank you!

**Comment by adrmnt** [comment]
@xyz4tech @atoree 
I've created this, for me is working, still testing it.
https://www.npmjs.com/package/homebridge-salus-it600-gateway

**Comment by xyz4tech** [comment]
@edlea Tried you plugin. Got no error but unfortunately no devices too. Anything to add in the configuration beside the credentials?
